
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_batch
    username: jason
    password: jason1653
  batch:
    jdbc:
      initialize-schema: always